- name: install required packages
  apt: pkg={{ item }} update_cache=yes
  with_items:
    - sudo
    - git
    - build-essential
    - curl

- name: install nl_NL.UTF-8 locale
  shell: locale-gen nl_NL.UTF-8

- name: set timezone variables
  copy: content='Europe/Amsterdam'
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
        backup=yes

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata
