- hosts: webserver
  sudo: yes
  roles:
    - {role: base, tags: ['base']}
    - {role: developer_access, tags: ['developer_access']}
    - {role: panicbutton_webhost, tags: ['panicbutton_webhost']}
    - {role: php, tags: ['php']}
    - role: nginx
      nginx_http_params:
        - sendfile on
        - access_log /var/log/nginx/access.log
        - error_log /var/log/nginx/error.log
      nginx_sites:
        panicbutton:
          - listen 80
          - server_name push.thepanicbutton.nl
          - root /usr/share/nginx/panicbutton
          - index index.php
          - location / {try_files $uri $uri/ /index.php; fastcgi_index index.php; fastcgi_pass unix:/var/run/php5-fpm.sock; fastcgi_split_path_info ^(.+\.php)(/.*)$; include fastcgi_params; fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name; fastcgi_param HTTPS off;}
      nginx_configs:
         gzip:
          - gzip on
          - gzip_disable msie6
      tags: ['nginx']

- hosts: elastic
  sudo: yes
  roles:
    - {role: base, tags: ['base']}
    - {role: developer_access, tags: ['developer_access']}
    - {role: docker, tags: ['docker']}

